package server;

/**
 * This class provides an abstract exception that can be generated by any magic
 * server. This can be used to "wrap" other exceptions generated by server
 * implementations.
 */
public class MagicServerException extends Exception{

    /**I honestly have no idea why I need this here*/
    private static final long serialVersionUID = 1L;

    /**
     * Creates a new MagicServerException with no message.
     */
    public MagicServerException(){}

    /**
     * Creates a new MagicServerException with the specified message.
     * @param message The error message to display to the user
     */
    public MagicServerException(String message){
        System.out.println(message);
    }

    /**
     * Creates a new MagicServerException that wraps the specified Throwable object.
     * @param throwable A throwable object to wrap with MagicSeverException
     */
    public MagicServerException(Throwable throwable){
        //Future implementation: pipe this to a log file
    }
    
    /**
     * Creates a new MagicServerException with the specified message, and wraps
     * the specified Throwable object.
     * @param message The error message to display to the user
     * @param throwable A throwable object to wrap with MagicSeverException
     */
    public MagicServerException(String message, Throwable throwable){
        System.out.println(message);
    }

}
